# Actividad - Trabajando con DataFrames de Pandas.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: pandas_df_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter
* Deben trabajar con el datasets adjunto a la actividad

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

In [2]:
import pandas as pd
import sqlite3

#Aqui agrega la conexión a la base de datos
conn = sqlite3.connect('Salaries.sqlite')

#Crea el dataframe con los datos del datasets
df = pd.read_sql_query("SELECT * FROM Salaries", conn)

conn.close()

df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,None,567595.43,567595.43,2011,None,San Francisco,None
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,None,538909.28,538909.28,2011,None,San Francisco,None
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,None,335279.91,335279.91,2011,None,San Francisco,None
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,None,332343.61,332343.61,2011,None,San Francisco,None
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,None,326373.19,326373.19,2011,None,San Francisco,None

1. **Top 10 empleados con mayor salario total (incluyendo beneficios)**
Extrae e imprime un top 10 de expleados con mayor salario incluyendo los beneficios

In [ ]:
#todo

df.sort_values('TotalPayBenefits', ascending=False, ignore_index=True)[['EmployeeName', 'TotalPayBenefits']].head(10) #Se usa "df" para seleccionar la tabla de la db y "sort_values" para ordenar los datos de la columna "TotalPayBenefits" de mayor a menor (ascending=False).Se muestran las columnas "EmployeeName" y "TotalPayBenefits" y se usa "head(10)" para mostrar solo los primeros 10 resultados.

           EmployeeName  TotalPayBenefits
0        NATHANIEL FORD         567595.43
1          GARY JIMENEZ         538909.28
2           David Shinn         510732.68
3            Amy P Hart         479652.21
4  William J Coaker Jr.         436224.36
5        Gregory P Suhr         425815.28
6  Joanne M Hayes-White         422353.40
7        Gregory P Suhr         418019.22
8  Joanne M Hayes-White         417435.10
9       Ellen G Moffatt         415767.94

2. **Filtrar empleados con más de 50,000 en horas extra, la columna a tratar es: (OvertimePay)**

In [ ]:
#todo

df["OvertimePay"] = pd.to_numeric(df["OvertimePay"], errors='coerce') #Convierte la columna "OvertimePay" a tipo numérico, manejando errores como NaN.

df[df["OvertimePay"] > 50000] #Filtra el dataframe para mostrar solo las filas donde "OvertimePay" es mayor a 50000.

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,None,538909.28,538909.28,2011,None,San Francisco,None
36159,36160,Gary Altenberg,"Lieutenant, Fire Suppression",128808.87,220909.48,13126.31,44430.12,362844.66,407274.78,2012,None,San Francisco,None
72927,72928,Samson Lai,"Battalion Chief, Fire Suppress",186236.42,131217.63,29648.27,57064.95,347102.32,404167.27,2013,None,San Francisco,None
72930,72931,David L Franklin,Asst Chf of Dept (Fire Dept),215265.6,87985.24,30637.48,62890.36,333888.32,396778.68,2013,None,San Francisco,None
110539,110540,Samson Lai,"Battalion Chief, Fire Suppress",179464.14,128685.99,27334.83,59876.9,335484.96,395361.86,2014,None,San Francisco,FT
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5686,5687,KEN YAO,TRANSIT OPERATOR,65275.49,53374.79,1903.51,None,120553.79,120553.79,2011,None,San Francisco,None
5864,5865,BYRON DUHON,"COUNSELOR, LOG CABIN RANCH",65215.26,51711.79,2572.97,None,119500.02,119500.02,2011,None,San Francisco,None
6144,6145,FELIX PAGATPATAN,TRANSIT OPERATOR,66863.99,50885.94,181.71,None,117931.64,117931.64,2011,None,San Francisco,None
7949,7950,SUNNY WONG,CLERK,46386.4,57036.75,4106.29,None,107529.44,107529.44,2011,None,San Francisco,None
55087,55088,Kimberley King-Stitt,Medical Evaluations Assistant,27390.72,51207.13,2647.02,18438.43,81244.87,99683.30,2012,None,San Francisco,None

3. **Contar cuántos empleados únicos hay por año**

In [ ]:
#todo

df.groupby("Year")["EmployeeName"].nunique() #Agrupa el dataframe por "Year" y cuenta el número de nombres únicos de empleados en cada año.

Year
2011    33878
2012    34349
2013    36150
2014    36684
Name: EmployeeName, dtype: int64

4. **Ver cuántos cargos únicos (JobTitle) existen y los 5 más comunes**

In [17]:
#todo

cargos = df["JobTitle"].nunique() #Cuenta el número de títulos de trabajo únicos en el dataframe.

print('\nNúmero de títulos de trabajo únicos:\n') #Imprime el número de títulos de trabajo únicos.
print(cargos) #Imprime el número de títulos de trabajo únicos.

df["JobTitle"].value_counts().head() #Cuenta la frecuencia de cada título de trabajo y muestra los 5 más comunes.

Número de títulos de trabajo únicos:

2159

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

5. **Mostrar el salario total (TotalPay) promedio por año**

In [ ]:
#todo

df.groupby("Year")["TotalPay"].mean().round(2) #Agrupa el dataframe por Año con el salario total promedio de cada uno.

Year
2011    71744.10
2012    74113.26
2013    77611.44
2014    75463.92
Name: TotalPay, dtype: float64

6. **Exporta todos los datos a un CSV y muestra los ultimos 10 valores**

In [ ]:
#todo